Repository satanb4/physionix, pull requests merged in 2023-04, with the labels that each got.

#10 EMG Filtering and Threads
  .gitignore
  README.md
  build.sh
  installdependencies.sh
  packages/fftw-3.3.10.tar.gz
  scripts/installdependencies.sh
  src/EMGProcessing/EMG_Signal.cpp
  src/EMGProcessing/emg_filter.cpp
  src/EMGProcessing/include/EMG_Signal.h
  src/EMGProcessing/include/emg_filter.h
  src/EMGProcessing/sample-application/Makefile
  src/EMGSensor/sample-application/Makefile
  src/EMGSensor/unittest/output
Labels: enhancement

#14 [#13] Fix issue with build script
  build.sh
Labels: bug

#15 Build scripts for physionix
  src/EMGData/EMGdata.cpp
  src/EMGData/EMGdata.h
  src/EMGProcessing/emg_filter.h
  src/EMGSensor/ADS1115.h
  src/EMGSensor/sample-application/main.cpp
  src/Makefile
  src/main.cpp
Labels: enhancement

#20 Bug fix for #17
  src/EMGSensor/ADS1115.cpp
Labels: bug

#21 Create CI for Physionix [#22]
  .github/workflows/c-cpp.yml
Labels: enhancement

#19 [#18] Fix for pigpio library missing in raspbian
  scripts/installdependencies.sh
Labels: bug

#23 Fix installation of Pigpio on actions
  .github/workflows/c-cpp.yml
  .gitignore
  build.sh
  scripts/installdependencies.sh
Labels: bug, enhancement

#25 [#22] Fixed check for actions
  scripts/installdependencies.sh
Labels: bug

#26 Fixed build to output directory
  build.sh
Labels: bug

#27 Movement deduction
  src/EMGProcessing/emg_filter.cpp
  src/EMGProcessing/emg_filter.h
Labels: enhancement

#28 Fixed readme file
  README.md
Labels: documentation

#29 Added web server for visualization of data
  .gitignore
  build.sh
  scripts/installdependencies.sh
  src/EMGApi/CMakeLists.txt
  src/EMGApi/EMGSensor.h
  src/EMGApi/emg_server.cpp
  src/EMGApi/fastcgi/CMakeLists.txt
  src/EMGApi/fastcgi/json_fastcgi_web_api.h
  src/EMGApi/website/README.md
  src/EMGApi/website/include/main.js
  src/EMGApi/website/index.html
  src/EMGApi/website/nginx-sites-enabled-default
  src/EMGApi/website/setup.sh
Labels: enhancement

#32 Application for process module testing and other changes
  .gitignore
  src/EMGData/EMGdata.cpp
  src/EMGData/EMGdata.h
  src/EMGProcessing/emg_filter.cpp
  src/EMGProcessing/emg_filter.h
  src/EMGProcessing/sample-application/Makefile
  src/EMGProcessing/sample-application/main.cpp
Labels: bug

#35 Fix for setup script of webserver
  src/EMGApi/website/setup.sh
Labels: bug

#34 [#31] Fix for filtering of lowPassData
  src/EMGProcessing/emg_filter.cpp
  src/EMGProcessing/emg_filter.h
  src/EMGProcessing/sample-application/Makefile
  src/EMGProcessing/sample-application/main.cpp
Labels: bug

#36 EMG Actuation
  src/EMGActuation/EMGActuation.cpp
  src/EMGActuation/MakeFile
Labels: enhancement

#39 Added thread functions for WebCGI
  .gitignore
  README.md
  media/Physionix-logo/cover.png
  media/Physionix-logo/default.png
  media/Physionix-logo/info.txt
  media/Physionix-logo/profile.png
  media/Physionix-logo/vector/default-monochrome-black.svg
  media/Physionix-logo/vector/default-monochrome-white.svg
  media/Physionix-logo/vector/default-monochrome.svg
  media/Physionix-logo/vector/default.svg
  media/Physionix-logo/vector/isolated-layout.svg
  media/Physionix-logo/vector/isolated-monochrome-black.svg
  media/Physionix-logo/vector/isolated-monochrome-white.svg
  src/EMGApi/EMGSensor.h
  src/EMGApi/emg_server.cpp
  src/EMGData/EMGdata.cpp
  src/EMGData/EMGdata.h
  src/EMGProcessing/emg_filter.cpp
  src/Makefile
Labels: enhancement

#38 Added README changes
  README.md
Labels: documentation

#41 Fixed Server API showing data
  src/EMGApi/EMGSensor.h
  src/EMGApi/emg_server.cpp
  src/EMGApi/website/include/main.js
  src/EMGApi/website/index.html
  src/EMGApi/website/setup.sh
Labels: bug

#43 Update README.md
  README.md
Labels: documentation

#46 Fixed EMGServer
  src/EMGData/EMGdata.cpp
  src/EMGData/EMGdata.h
  src/Makefile
Labels: bug, enhancement
